### PR TITLE
sanctuary-type-classes@1.1.x

### PR DESCRIPTION
**Pull request by davidchambers**
https://github.com/sanctuary-js/sanctuary-type-classes/compare/v0.3.0...v1.1.0

### CODE REVIEW

**Comment by safareli** [comment]
I'm committing changes on `dev` branch, so I have changed target branch to `dev`, but as your base branch was `master`  now it includes some merge commits. can you fix it? (dont know how :d)

I'm still working on rewrite and if you don't want to spend your time on this issue no problem! Thanks tho!

**Comment by safareli** [comment]
I'm committing changes on `dev` branch, so I have changed target branch to `dev`, but as your base branch was `master`  now it includes some merge commits. can you fix it? (dont know how :d)

I'm still working on rewrite and if you don't want to spend your time on this issue no problem!

**Comment by davidchambers** [comment]
> I have changed target branch to `dev`

I had no idea GitHub supports this. Very cool!

> I'm still working on rewrite and if you don't want to spend your time on this issue no problem!

It's not a problem. I've updated the pull request. :)

**Comment by davidchambers** [comment]
Shall I update this pull request to use `sanctuary-type-classes@1.1.x`, @safareli?

**Comment by safareli** [comment]
Would be nice! and will merge this weekend

**Comment by davidchambers** [comment]
:zap:

**Pull request merged**
